{{$HostNetworkMode := DefaultParam .CL2_USE_HOST_NETWORK_PODS false}}
{{$Image := DefaultParam .Image "registry.k8s.io/pause:3.9"}}
{{$Env := DefaultParam .Env ""}}
{{$DaemonSetSurge := DefaultParam .CL2_DS_SURGE (MaxInt 10 (DivideInt .Nodes 20))}} # 5% of nodes, but not less than 10
{{$RUN_ON_ARM_NODES := DefaultParam .CL2_RUN_ON_ARM_NODES false}}

{{$ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST := DefaultParam .CL2_ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST false}}
{{$NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_KEY := DefaultParam .CL2_NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_KEY "test"}}
{{$NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_VALUE := DefaultParam .CL2_NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_VALUE "net-policy-client"}}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Name}}
  labels:
    group: load
    multinetwork8: "true"
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{$DaemonSetSurge}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: load
        name: {{.Name}}
        multinetwork8: "true"
      annotations:
        networking.gke.io/default-interface: 'eth0'
        networking.gke.io/interfaces: |
          [
            {
              "interfaceName": "eth0",
              "network": "default"
            },
            {
              "interfaceName": "eth1",
              "network": "net8-sub8-sec1"
            },
            {
              "interfaceName": "eth2",
              "network": "net8-sub8-sec2"
            },
            {
              "interfaceName": "eth3",
              "network": "net8-sub8-sec3"
            },
            {
              "interfaceName": "eth4",
              "network": "net8-sub8-sec4"
            },
            {
              "interfaceName": "eth5",
              "network": "net8-sub8-sec5"
            },
            {
              "interfaceName": "eth6",
              "network": "net8-sub8-sec6"
            },
            {
              "interfaceName": "eth7",
              "network": "net8-sub8-sec7"
            },
            {
              "interfaceName": "eth8",
              "network": "net8-sub8-sec0"
            }
          ]
    spec:
      nodeSelector:
        multinetwork8: "true"
      hostNetwork: {{$HostNetworkMode}}
      containers:
      - name: {{.Name}}
        image: {{$Image}}
        env:
          - name: TEST_ENV
            value: {{$Env}}
        resources:
          # Keep the CpuRequest/MemoryRequest request equal percentage of 1-core, 4GB node.
          # For now we're setting it to 0.5%.
          requests:
            cpu: 5m
            memory: "20M"
      priorityClassName: daemonset-priorityclass-0 # Name is autogenerated, hence the -0 prefix.
      terminationGracePeriodSeconds: 1
      tolerations: 
      {{if $RUN_ON_ARM_NODES}}
      - key: "kubernetes.io/arch"
        operator: Equal
        value: arm64
        effect: NoSchedule
      {{end}}
      {{if $ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST}}
      - key: {{$NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_KEY}}
        operator: Equal
        value: {{$NET_POLICY_ENFORCEMENT_LATENCY_NODE_LABEL_VALUE}}
        effect: NoSchedule
      {{end}}
