{{$Image := DefaultParam .Image "registry.k8s.io/pause:3.9"}}
{{$RUN_ON_ARM_NODES := DefaultParam .CL2_RUN_ON_ARM_NODES false}}
{{$EnableMNAnnotation := DefaultParam .CL2_ENABLE_MN_ANNOTATION true}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  labels:
    group: aiml
spec:
  podManagementPolicy: Parallel
  replicas: {{RandIntRange .ReplicasMin .ReplicasMax}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: aiml
        name: {{.Name}}
      annotations:
        networking.gke.io/default-interface: 'eth0'
        networking.gke.io/interfaces: |
          [
            {
              "interfaceName": "eth0",
              "network": "default"
            },
            {
              "interfaceName": "eth1",
              "network": "mn-net1"
            },
            {
              "interfaceName": "eth2",
              "network": "mn-net2"
            },
            {
              "interfaceName": "eth3",
              "network": "mn-net3"
            },
            {
              "interfaceName": "eth4",
              "network": "mn-net4"
            }
          ]
    spec:
      schedulerName: gke.io/first-fit
      containers:
      - name: {{.Name}}
        image: {{$Image}}
        resources:
          requests:
            cpu: 5m
            memory: "20M"
      terminationGracePeriodSeconds: 1
      tolerations:
  serviceName: svc-{{.Name}}
